### ISSUE TITLE
deprecation

### ISSUE THREAD

**Issue by aehm2k5** [raffaelj/cockpit_FormValidation#3]
idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated in <b> cockpit/addons/FormValidation/Helper/Validator.php</b> on line <b>239</b>
not compatible with php 7.3.13

```php
            case 'mail':
                return filter_var(idn_to_ascii($this->data[$field]), FILTER_VALIDATE_EMAIL);

            case 'phone':
                return !preg_match('~[^-\s\d./()+]~', $this->data[$field]);

            case 'url':
                return filter_var(idn_to_ascii($this->data[$field]), FILTER_VALIDATE_URL);
 ```
fix
 
```php
            case 'mail':
                return filter_var(idn_to_ascii($this->data[$field], IDNA_NONTRANSITIONAL_TO_ASCII, INTL_IDNA_VARIANT_UTS46), FILTER_VALIDATE_EMAIL);

            case 'phone':
                return !preg_match('~[^-\s\d./()+]~', $this->data[$field]);

            case 'url':
                return filter_var(idn_to_ascii($this->data[$field], IDNA_NONTRANSITIONAL_TO_ASCII, INTL_IDNA_VARIANT_UTS46), FILTER_VALIDATE_URL);
 ```

in bootstrap.php Line 64

```php
filter_var(
            idn_to_ascii(trim($data[$frm['reply_to']])), FILTER_VALIDATE_EMAIL)
```

fix

```php
filter_var(
            idn_to_ascii(
                trim($data[$frm['reply_to']])
                , IDNA_NONTRANSITIONAL_TO_ASCII, INTL_IDNA_VARIANT_UTS46
            ), FILTER_VALIDATE_EMAIL)
```

**Comment by raffaelj** [comment]
Thanks for the issue and for the fix.

**Comment by raffaelj** [comment]
Note to my future self - If I'm confused about `idn_to_ascii()` and php versions again and because I used the same validator in a different project without the update:

Everything works with and without the change if errors are suppressed. It also only effects PHP 7.2 and PHP 7.3. Since PHP 7.4, `INTL_IDNA_VARIANT_UTS46` is the default and the deprecation warning disappears.

See also: https://www.php.net/manual/en/function.idn-to-ascii.php#refsect1-function.idn-to-ascii-changelog
